### ISSUE TITLE
README doesn't specify API key location

### ISSUE THREAD

**Issue by mrjohnyhats** [sunmockyang/puush-linux#11]
I spent around an hour fiddling with the script because it wasn't uploading my image. Found that I just copied the wrong API key after around an hour and internally slow-clapped for myself. I think that specifying the API key's location in greater detail in the README wouldn't be a bad idea.

**Comment by sunmockyang** [comment]
Glad you found the API key eventually, but, I think it's pretty clear in the README though. You just go to the page I linked, and it's under Account, API Key. :) Happy puushing
