### ISSUE TITLE
printf: -1: invalid option

### ISSUE THREAD

**Issue by Eschon** [sunmockyang/puush-linux#8]
When I try to take a screenshot I get the following error:

```
/usr/local/bin/puush: line 51: printf: -1: invalid option
printf: usage: printf [-v var] format [arguments]
Unknown option -1
```
And the sceenshot does not appear in my puush gallery.

**Comment by sunmockyang-youi** [comment]
Try wrapping `$fileURL` in quotation marks. See if that works. https://github.com/sunmockyang/puush-linux/blob/master/puush#L51

**Comment by sunmockyang-youi** [comment]
If so, let me know so I can fix it, or make a PR. If not, try adding `echo "$fileURL` in the line before and lemme know what the output is.

**Comment by sunmockyang** [comment]
Try wrapping $fileURL in quotation marks. See if that works. https://github.com/sunmockyang/puush-linux/blob/master/puush#L51

**Comment by sunmockyang** [comment]
If so, let me know so I can fix it, or make a PR. If not, try adding echo "$fileURL in the line before and lemme know what the output is.

**Comment by Eschon** [comment]
Wrapping `$fileURL` in quotation marks did not fix the problem.The output for `echo "$fileURL"` is -1

**Comment by Eschon** [comment]
Maybe I made a mistake when copying the api key. In my puush account under settings there is "Third Party Support". There I found the API endpoint. Is that what I need to copy into the PUUSH_API_KEY?

**Comment by sunmockyang-youi** [comment]
No, under Account, there's an `API Key: hover to display`. You can get it from that

**Comment by sunmockyang** [comment]
No, under Account, there's an API Key: hover to display. You can get it from that

**Comment by sunmockyang** [comment]
Let me know if it worked or not

**Comment by Eschon** [comment]
It works with the correct API key.
Thanks

**Comment by sunmockyang** [comment]
Awesome. Happy puushing
