### ISSUE TITLE
Puushing causes html instead of a url.

### ISSUE THREAD

**Issue by alextpedro** [sunmockyang/puush-linux#9]
This happened in 2/3 tries today. No idea what might be causing it.
![screenshot from 2016-01-24 00 23 08](https://cloud.githubusercontent.com/assets/5782944/12533751/a71c72a2-c232-11e5-82e3-285714a22e25.png)

**Comment by sunmockyang** [comment]
Can you run the script in terminal and paste the entire output + the command here?

**Comment by sunmockyang** [comment]
To me it looks like the puush's API is failing, but I wanted to double check. Do 1/3 of your screenshots make it through to puush?

**Comment by alextpedro** [comment]
Strangest thing, this stopped occurring the next day. Maybe the API did fail, in which case, sorry to bother!

**Comment by sunmockyang** [comment]
Marking this as closed as it was API issues.
